#!/usr/bin/env python3
"""
Fetches the Material Symbols (Rounded, filled, weight 400; Apache License 2.0, google/material-design-icons) the shade
draws and writes them as vector drawables: app/src/main/res/drawable/sym_<name>.xml (white; tinted at draw time).
Re-run after adding a name below. The generated files are committed; the build does not need the network.

    python tools/fetch_symbols.py
"""
import os
import re
import sys
import urllib.request

# name in the Material Symbols repository -> our drawable name (sym_<ours>)
SYMBOLS = {
    "airplanemode_active": "airplane",
    "wifi": "wifi",
    "bluetooth": "bluetooth",
    "cell_tower": "cellular",
    "wifi_tethering": "hotspot",
    "near_me": "location",
    "nfc": "nfc",
    "screen_lock_rotation": "rotation_lock",
    "screen_rotation": "rotation",
    "notifications": "bell",
    "notifications_off": "bell_off",
    "bedtime": "moon",
    "flashlight_on": "flashlight",
    "av_timer": "timer",
    "timer": "stopwatch",
    "alarm": "alarm",
    "calculate": "calculator",
    "photo_camera": "camera",
    "cast": "mirroring",
    "qr_code_scanner": "qr",
    "light_mode": "sun",
    "volume_up": "volume",
    "volume_off": "volume_off",
    "play_arrow": "play",
    "pause": "pause",
    "fast_forward": "forward",
    "fast_rewind": "rewind",
    "airplay": "airplay",
    "power_settings_new": "power",
    "add": "plus",
    "remove": "minus",
    "close": "close",
    "contrast": "dark_mode",
    "battery_saver": "low_power",
    "edit_note": "note",
    "radio_button_checked": "record",
    "unfold_more": "unfold",
    "chevron_right": "chevron",
    "favorite": "heart",
    "music_note": "music",
    "search": "search",
    "more_horiz": "more",
    "bed": "bed",
    "settings": "settings",
    "vpn_key": "vpn",
    "data_saver_on": "data_saver",
    "screen_record": "screen_record",
    "keyboard_arrow_down": "arrow_down",
    "call": "call",
    "call_end": "call_end",
    # More of iOS's controls, as Android has them.
    "format_size": "text_size",
    "invert_colors": "invert",
    "filter_b_and_w": "grayscale",
    "brightness_low": "extra_dim",
    "closed_caption": "captions",
    "mic": "mic",
    "zoom_in": "magnifier",
    "translate": "translate",
    "graphic_eq": "recognize_music",
    "videocam": "video",
    "camera_front": "selfie",
    "account_balance_wallet": "wallet",
    "home": "home",
    "share": "share",
    "accessibility_new": "accessibility",
    "hearing": "hearing",
}

URL = "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/{0}/materialsymbolsrounded/{0}_fill1_24px.svg"

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols Rounded "{src}" (filled), Apache License 2.0, Google. Generated by tools/fetch_symbols.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
        <path
            android:fillColor="#FFFFFFFF"
            android:pathData="{path}" />
    </group>
</vector>
"""


def main():
    out = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res", "drawable")
    failed = []
    for src, ours in SYMBOLS.items():
        try:
            svg = urllib.request.urlopen(URL.format(src), timeout=20).read().decode("utf-8")
            paths = re.findall(r'<path[^>]* d="([^"]+)"', svg)
            if not paths:
                raise ValueError("no path")
            with open(os.path.join(out, "sym_%s.xml" % ours), "w", encoding="utf-8", newline="\n") as f:
                f.write(TEMPLATE.format(src=src, path=" ".join(paths)))
            print("ok   %-22s -> sym_%s" % (src, ours))
        except Exception as e:  # keep going: report all failures at the end
            failed.append(src)
            print("FAIL %-22s %s" % (src, e))
    if failed:
        sys.exit("failed: " + ", ".join(failed))


if __name__ == "__main__":
    main()
